### ISSUE TITLE
Failed to display output on Jetson Nano

### ISSUE THREAD

**Issue by TClan8023** [NVIDIA-AI-IOT/deepstream_tlt_apps#20]
hi,
I have followed the steps described to install TensorRT OSS and deepstream-tlt-apps on my Nano (TRT 7.0, DeepStream 5.0 and CUDA 10.2, JetPack 4.4) and both the libraries were built successfuly and updated the .so file libnvinfer_plugin.so.7.0.0.1 to the folder /usr/lib/aarch64-linux-gnu/. However when I tried to run the example application for frcnn (./deepstream-custom  -c pgie_frcnn_tlt_config.txt -i $DS_SRC_PATH/samples/streams/sample_720p.h264). Model engine has been created successfully but I  still get the following error:
#assertion .../TensorRT/plugin/common/kernels/proposalKernel.cu,709 Aborted (core dumped)

Complete output infomation shows below:
Now playing: pgie_frcnn_tlt_config.txt
Opening in BLOCKING MODE 
0:00:00.312834850  7163   0x5589b21e70 INFO                 nvinfer gstnvinfer.cpp:602:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1591> [UID = 1]: Trying to create engine from model files
INFO: [TRT]: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
INFO: [TRT]: Detected 1 inputs and 3 output network tensors.
0:00:36.675326788  7163   0x5589b21e70 INFO                 nvinfer gstnvinfer.cpp:602:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1624> [UID = 1]: serialize cuda engine to file: /home/iot/Downloads/deepstream_tlt_apps-master/models/frcnn/faster_rcnn_resnet10.etlt_b1_gpu0_fp16.engine successfully
INFO: [Implicit Engine Info]: layers num: 4
0   INPUT  kFLOAT input_image     3x272x480       
1   OUTPUT kFLOAT proposal        300x4x1         
2   OUTPUT kFLOAT dense_regress_td/BiasAdd 300x16x1x1      
3   OUTPUT kFLOAT dense_class_td/Softmax 300x5x1x1       

0:00:36.733242280  7163   0x5589b21e70 INFO                 nvinfer gstnvinfer_impl.cpp:311:notifyLoadModelStatus:<primary-nvinference-engine> [UID 1]: Load new model:pgie_frcnn_tlt_config.txt sucessfully
Running...
NvMMLiteBlockCreate : Block : BlockType = 256 
[JPEG Decode] BeginSequence Display WidthxHeight 1280x720
#assertion/home/iot/Downloads/TensorRT/plugin/common/kernels/proposalKernel.cu,709
Aborted (core dumped)

Any information will be appreciated, thanks a lot.

**Comment by TClan8023** [comment]
It seems that there are some errors in function nms, for all examples (ssd, dssd, frcnn, retina, yolov3), their outputs show the following error: #assertion/home/iot/Downloads/TensorRT/plugin/nmsPlugin/nmsPlugin.cpp,118
Aborted (core dumped)
or
#assertion/home/iot/Downloads/TensorRT/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp,116
Aborted (core dumped)

**Comment by jtagxhub** [comment]
To be exact, are you using **JetPack 4.4GA** or JetPack 4.4DP ?

**Comment by TClan8023** [comment]
> To be exact, are you using **JetPack 4.4GA** or JetPack 4.4DP ?

Sorry, I don't know the difference between 4.4 GA and 4.4 DP, how can I check it?
By the way, for my case, I solved the problems by changing the TRT_PLATFORM_ID in CMakeLists.txt from the default "x86_64" to "aarch64" because my device is Jetson nano and the platform should be aarch64.
